.TH "FABTESTS" 7 "2014-02-21" "libfabric" "libfabric Tests" libfabric
.SH NAME
fabtests \- libfabric test programs
.PP
fi_pingpong - simple message pingpong test
.SH "SIMPLE TESTS"
The following tests are very simple in nature and can be used as
sample programs to understand the libfabric interfaces and how
they are used.
.SS fi_pingpong
.SH "SEE ALSO"
fabric(7)
