.TH "FI_SOCKET" 3 "2013-11-01" "libfabric" "Libfabric Programmer's Manual" libfabric
.SH NAME
fi_socket / fi_close \- Allocate/close a fabric interface socket
.SH SYNOPSIS
.B "#include <rdma/fabric.h>"
.P
.B "int" fi_socket
.BI "(struct fi_info *" info ","
.BI "fid_t *" fid ","
.BI "void *" context ");"
.P
.B "int" fi_close
.BI "(fid_t " fid ");"
.SH ARGUMENTS
.IP "info" 12
Details about the fabric interface socket to be opened. 
.IP "fid" 12
On success, points to the opened fabric socket.
.IP "context" 12
User specified context associated with the socket.
.SH "DESCRIPTION"
Opens a fabric interface socket.
.SH "RETURN VALUE"
Returns 0 on success, or errno on error.
.SH "NOTES"
Opens a fabric socket corresponding to the requested fabric interface
information.  Users should call fi_close to release all resources allocated
fo the fabric socket.
.SH "SEE ALSO"
fi_getinfo(3), fi_open(3)
