if HAVE_USNIC
libusnic_direct_sources = \
	prov/usnic/src/usnic_direct/cq_desc.h \
	prov/usnic/src/usnic_direct/cq_enet_desc.h \
	prov/usnic/src/usnic_direct/kcompat.h \
	prov/usnic/src/usnic_direct/kcompat_priv.h \
	prov/usnic/src/usnic_direct/libnl1_utils.h \
	prov/usnic/src/usnic_direct/libnl3_utils.h \
	prov/usnic/src/usnic_direct/libnl_utils_common.c \
	prov/usnic/src/usnic_direct/libnl_utils.h \
	prov/usnic/src/usnic_direct/linux/delay.h \
	prov/usnic/src/usnic_direct/linux/slab.h \
	prov/usnic/src/usnic_direct/linux_types.h \
	prov/usnic/src/usnic_direct/rq_enet_desc.h \
	prov/usnic/src/usnic_direct/usd_caps.c \
	prov/usnic/src/usnic_direct/usd_caps.h \
	prov/usnic/src/usnic_direct/usd_dest.c \
	prov/usnic/src/usnic_direct/usd_dest.h \
	prov/usnic/src/usnic_direct/usd_device.c \
	prov/usnic/src/usnic_direct/usd_device.h \
	prov/usnic/src/usnic_direct/usd_event.c \
	prov/usnic/src/usnic_direct/usd.h \
	prov/usnic/src/usnic_direct/usd_ib_cmd.c \
	prov/usnic/src/usnic_direct/usd_ib_cmd.h \
	prov/usnic/src/usnic_direct/usd_ib_sysfs.c \
	prov/usnic/src/usnic_direct/usd_ib_sysfs.h \
	prov/usnic/src/usnic_direct/usd_mem.c \
	prov/usnic/src/usnic_direct/usd_poll.c \
	prov/usnic/src/usnic_direct/usd_post.c \
	prov/usnic/src/usnic_direct/usd_post.h \
	prov/usnic/src/usnic_direct/usd_post_ud_raw.c \
	prov/usnic/src/usnic_direct/usd_post_ud_udp.c \
	prov/usnic/src/usnic_direct/usd_post_ud_pio_udp.c \
	prov/usnic/src/usnic_direct/usd_queue.h \
	prov/usnic/src/usnic_direct/usd_queues.c \
	prov/usnic/src/usnic_direct/usd_socket.c \
	prov/usnic/src/usnic_direct/usd_socket.h \
	prov/usnic/src/usnic_direct/usd_time.h \
	prov/usnic/src/usnic_direct/usd_util.h \
	prov/usnic/src/usnic_direct/usd_vnic.c \
	prov/usnic/src/usnic_direct/usd_vnic.h \
	prov/usnic/src/usnic_direct/usnic_abi.h \
	prov/usnic/src/usnic_direct/usnic_direct.h \
	prov/usnic/src/usnic_direct/usnic_ib_abi.h \
	prov/usnic/src/usnic_direct/usnic_ip_utils.c \
	prov/usnic/src/usnic_direct/usnic_ip_utils.h \
	prov/usnic/src/usnic_direct/usnic_user_utils.h \
	prov/usnic/src/usnic_direct/vnic_cq.c \
	prov/usnic/src/usnic_direct/vnic_cq.h \
	prov/usnic/src/usnic_direct/vnic_dev.c \
	prov/usnic/src/usnic_direct/vnic_devcmd.h \
	prov/usnic/src/usnic_direct/vnic_dev.h \
	prov/usnic/src/usnic_direct/vnic_enet.h \
	prov/usnic/src/usnic_direct/vnic_resource.h \
	prov/usnic/src/usnic_direct/vnic_rq.c \
	prov/usnic/src/usnic_direct/vnic_rq.h \
	prov/usnic/src/usnic_direct/vnic_stats.h \
	prov/usnic/src/usnic_direct/vnic_wq.c \
	prov/usnic/src/usnic_direct/vnic_wq.h \
	prov/usnic/src/usnic_direct/vnic_intr.c \
	prov/usnic/src/usnic_direct/vnic_intr.h \
	prov/usnic/src/usnic_direct/wq_enet_desc.h

_usnic_files = \
	$(libusnic_direct_sources) \
	prov/usnic/src/fi_ext_usnic.h \
	prov/usnic/src/usdf.h \
	prov/usnic/src/usdf_av.c \
	prov/usnic/src/usdf_av.h \
	prov/usnic/src/usdf_cm.c \
	prov/usnic/src/usdf_cm.h \
	prov/usnic/src/usdf_cq.c \
	prov/usnic/src/usdf_cq.h \
	prov/usnic/src/usdf_dgram.c \
	prov/usnic/src/usdf_dgram.h \
	prov/usnic/src/usdf_domain.c \
	prov/usnic/src/usdf_endpoint.c \
	prov/usnic/src/usdf_endpoint.h \
	prov/usnic/src/usdf_ep_dgram.c \
	prov/usnic/src/usdf_ep_msg.c \
	prov/usnic/src/usdf_ep_rdm.c \
	prov/usnic/src/usdf_eq.c \
	prov/usnic/src/usdf_fabric.c \
	prov/usnic/src/usdf_mem.c \
	prov/usnic/src/usdf_msg.c \
	prov/usnic/src/usdf_msg.h \
	prov/usnic/src/usdf_pep.c \
	prov/usnic/src/usdf_progress.c \
	prov/usnic/src/usdf_progress.h \
	prov/usnic/src/usdf_rdm.c \
	prov/usnic/src/usdf_rdm.h \
	prov/usnic/src/usdf_rudp.h \
	prov/usnic/src/usdf_timer.c \
	prov/usnic/src/usdf_timer.h

if HAVE_VERBS
_usnic_files += prov/usnic/src/usdf_fake_ibv.c
endif

_usnic_cppflags = \
        -D__LIBUSNIC__ -DWANT_DEBUG_MSGS=0 \
        -DHAVE_LIBNL3=$(HAVE_LIBNL3) $(usnic_CPPFLAGS) \
        -I$(top_srcdir)/prov/usnic/src/usnic_direct

rdmainclude_HEADERS += \
	prov/usnic/src/fi_ext_usnic.h

if HAVE_USNIC_DL
pkglib_LTLIBRARIES += libusnic-fi.la
libusnic_fi_la_CPPFLAGS = $(AM_CPPFLAGS) $(_usnic_cppflags)
libusnic_fi_la_SOURCES = $(_usnic_files) $(common_srcs)
libusnic_fi_la_LDFLAGS = \
        $(usnic_ln_LDFLAGS) \
        -module -avoid-version -shared -export-dynamic
libusnic_fi_la_LIBADD = $(linkback) $(usnic_LIBS)
libusnic_fi_la_DEPENDENCIES = $(linkback)
else !HAVE_USNIC_DL
src_libfabric_la_SOURCES += $(_usnic_files)
src_libfabric_la_CPPFLAGS += $(_usnic_cppflags)
src_libfabric_la_LDFLAGS += $(usnic_LDFLAGS)
src_libfabric_la_LIBADD += $(usnic_LIBS)
endif !HAVE_USNIC_DL

prov_install_man_pages += man/man7/fi_usnic.7

endif HAVE_USNIC

prov_dist_man_pages += man/man7/fi_usnic.7
