#
# Copyright (c) 2021 Amazon.com, Inc. or its affiliates. All rights reserved.
#
# This software is available to you under a choice of one of two
# licenses.  You may choose to be licensed under the terms of the GNU
# General Public License (GPL) Version 2, available from the file
# COPYING in the main directory of this source tree, or the
# BSD license below:
#
#     Redistribution and use in source and binary forms, with or
#     without modification, are permitted provided that the following
#     conditions are met:
#
#      - Redistributions of source code must retain the above
#        copyright notice, this list of conditions and the following
#        disclaimer.
#
#      - Redistributions in binary form must reproduce the above
#        copyright notice, this list of conditions and the following
#        disclaimer in the documentation and/or other materials
#        provided with the distribution.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

if ENABLE_EFA
bin_PROGRAMS += prov/efa/src/fi_efa_rnr_read_cq_error \
		prov/efa/src/fi_efa_rnr_queue_resend \
		prov/efa/src/fi_efa_info_test \
		prov/efa/src/fi_efa_rdm_remote_exit_early \
		prov/efa/src/fi_efa_multi_ep_mt \
		prov/efa/src/fi_efa_implicit_av_test

if HAVE_VERBS_DEVEL
if HAVE_EFA_DV
bin_PROGRAMS += prov/efa/src/fi_efa_exhaust_mr_reg_rdm_pingpong
endif HAVE_EFA_DV
if BUILD_EFA_RDMA_CHECKER
bin_PROGRAMS += prov/efa/src/fi_efa_rdma_checker
endif BUILD_EFA_RDMA_CHECKER
if EFAGDA
bin_PROGRAMS += prov/efa/src/fi_efa_gda
endif EFAGDA
endif HAVE_VERBS_DEVEL

efa_rnr_srcs = \
	prov/efa/src/efa_shared.h \
	prov/efa/src/efa_rnr_shared.h \
	prov/efa/src/efa_rnr_shared.c

prov_efa_src_fi_efa_rnr_read_cq_error_SOURCES = \
	prov/efa/src/rdm_rnr_read_cq_error.c \
	$(efa_rnr_srcs)
prov_efa_src_fi_efa_rnr_read_cq_error_LDADD = libfabtests.la

prov_efa_src_fi_efa_rnr_queue_resend_SOURCES = \
	prov/efa/src/rdm_rnr_queue_resend.c \
	$(efa_rnr_srcs)
prov_efa_src_fi_efa_rnr_queue_resend_LDADD = libfabtests.la

prov_efa_src_fi_efa_info_test_SOURCES = \
	prov/efa/src/efa_info_test.c
prov_efa_src_fi_efa_info_test_LDADD = libfabtests.la

prov_efa_src_fi_efa_rdm_remote_exit_early_SOURCES = \
	prov/efa/src/rdm_remote_exit_early.c \
	$(efa_rnr_srcs)
prov_efa_src_fi_efa_rdm_remote_exit_early_LDADD = libfabtests.la

prov_efa_src_fi_efa_multi_ep_mt_SOURCES = \
	prov/efa/src/multi_ep_mt.c \
	$(efa_rnr_srcs)
prov_efa_src_fi_efa_multi_ep_mt_LDADD = libfabtests.la

prov_efa_src_fi_efa_implicit_av_test_SOURCES = \
	prov/efa/src/efa_shared.h \
	prov/efa/src/efa_implicit_av_test.c
prov_efa_src_fi_efa_implicit_av_test_LDADD = libfabtests.la

if HAVE_VERBS_DEVEL
if HAVE_EFA_DV
efa_exhaust_mr_reg_srcs = \
	prov/efa/src/efa_exhaust_mr_reg_common.h \
	prov/efa/src/efa_exhaust_mr_reg_common.c

prov_efa_src_fi_efa_exhaust_mr_reg_rdm_pingpong_SOURCES = \
	prov/efa/src/efa_exhaust_mr_reg_rdm_pingpong.c \
	$(efa_exhaust_mr_reg_srcs) \
	$(benchmarks_srcs)
prov_efa_src_fi_efa_exhaust_mr_reg_rdm_pingpong_LDADD = libfabtests.la
prov_efa_src_fi_efa_exhaust_mr_reg_rdm_pingpong_LDFLAGS = -lefa
endif HAVE_EFA_DV

if BUILD_EFA_RDMA_CHECKER
prov_efa_src_fi_efa_rdma_checker_SOURCES = \
	prov/efa/src/efa_rdma_checker.c
prov_efa_src_fi_efa_rdma_checker_LDADD = libfabtests.la
prov_efa_src_fi_efa_rdma_checker_LDFLAGS = -lefa
endif BUILD_EFA_RDMA_CHECKER

if EFAGDA
SUBDIRS += prov/efa/src/efagda
prov_efa_src_fi_efa_gda_SOURCES = prov/efa/src/efa_gda.c
prov_efa_src_fi_efa_gda_LDFLAGS = -Wl,-rpath=$(libdir)
prov_efa_src_fi_efa_gda_LDADD = -L$(libdir) -L/usr/local/cuda/lib64 -lefagda -lcudart -lcuda libfabtests.la
export prefix
install-efagda:
	$(MAKE) -C prov/efa/src/efagda install prefix=$(prefix)
endif EFAGDA

EXTRA_DIST += prov/efa/src/efagda

endif HAVE_VERBS_DEVEL
endif ENABLE_EFA
