/* SPDX-License-Identifier: BSD-2-Clause OR GPL-2.0-only */
/* SPDX-FileCopyrightText: Copyright Amazon.com, Inc. or its affiliates. All rights reserved. */

#include <assert.h>
#include <ofi_util.h>

#include "config.h"
#include "efa.h"
#include "efa_domain_util.h"

int efa_domain_init_base(struct efa_domain *efa_domain,
			 struct fid_fabric *fabric_fid,
			 struct fi_info *info,
			 void *context)
{
	int err;

	/* This list_entry is not the head of the list. But we initialize it
	 * anyway to prevent a segfault in the close path: dlist_remove on a
	 * self-looped entry is a no-op, so a partial-init close that runs
	 * before insertion into g_efa_domain_list is safe.
	 */
	dlist_init(&efa_domain->list_entry);
	efa_domain->fabric = container_of(fabric_fid, struct efa_fabric,
					  util_fabric.fabric_fid);

	err = ofi_domain_init(fabric_fid, info, &efa_domain->util_domain,
			      context, OFI_LOCK_MUTEX);
	if (err)
		return err;

	ofi_atomic_initialize64(&efa_domain->ibv_mr_reg_ct, 0);
	ofi_atomic_initialize64(&efa_domain->ibv_mr_reg_sz, 0);

	efa_domain->ah_map = NULL;

	efa_domain->util_domain.av_type = FI_AV_TABLE;
	efa_domain->util_domain.mr_map.mode |= FI_MR_VIRT_ADDR;
	/*
	 * FI_MR_PROV_KEY means provider will generate a key for MR,
	 * which EFA provider does by using key generated by EFA device.
	 *
	 * util_domain.mr_map.mode is same as info->mode, which has
	 * the bit FI_MR_PROV_KEY on. When the bit is on, util_domain.mr_map
	 * will generate a key for MR, which is not what we want
	 * (we want to use the key generated by device). Therefore unset
	 * the FI_MR_PROV_KEY bit of mr_map.
	 */
	efa_domain->util_domain.mr_map.mode &= ~FI_MR_PROV_KEY;

	if (!info->ep_attr || info->ep_attr->type == FI_EP_UNSPEC) {
		EFA_WARN(FI_LOG_DOMAIN, "ep type not specified when creating domain\n");
		return -FI_EINVAL;
	}

	efa_domain->mr_local = ofi_mr_local(info);

	err = efa_domain_init_device_and_pd(efa_domain, info->domain_attr->name,
					    info->ep_attr->type);
	if (err)
		return err;

	efa_domain->info = fi_dupinfo(EFA_EP_TYPE_IS_RDM(info)
				      ? efa_domain->device->rdm_info
				      : efa_domain->device->dgram_info);
	if (!efa_domain->info)
		return -FI_ENOMEM;

	/* keep max_cntr_value and max_err_cntr_value from user info so we can
	 * decide whether to use hw counter later */
	efa_domain->info->domain_attr->max_cntr_value = info->domain_attr->max_cntr_value;
	efa_domain->info->domain_attr->max_err_cntr_value = info->domain_attr->max_err_cntr_value;

	if (efa_env.track_mr)
		dlist_init(&efa_domain->base_ep_list);

	return 0;
}

int efa_domain_finalize_base(struct efa_domain *efa_domain)
{
#ifndef _WIN32
	int err = efa_fork_support_install_fork_handler();
	if (err) {
		EFA_WARN(FI_LOG_CORE,
			 "Unable to install fork handler: %s\n",
			 strerror(-err));
		return err;
	}
#endif

	ofi_mutex_lock(&g_efa_domain_list_lock);
	dlist_insert_tail(&efa_domain->list_entry, &g_efa_domain_list);
	ofi_mutex_unlock(&g_efa_domain_list_lock);

	return 0;
}

void efa_domain_remove_from_global_list(struct efa_domain *efa_domain)
{
	ofi_mutex_lock(&g_efa_domain_list_lock);
	dlist_remove(&efa_domain->list_entry);
	ofi_mutex_unlock(&g_efa_domain_list_lock);
}

void efa_domain_cleanup_ah_map(struct efa_domain *efa_domain)
{
	struct efa_ah *ah_entry, *tmp;
	int ret;

	ofi_genlock_lock(&efa_domain->util_domain.lock);
	if (efa_domain->ah_map) {
		EFA_WARN(FI_LOG_DOMAIN, "AH map not empty during domain close! Cleaning up ...\n");
		HASH_ITER(hh, efa_domain->ah_map, ah_entry, tmp) {
			ret = ibv_destroy_ah(ah_entry->ibv_ah);
			if (ret)
				EFA_WARN(FI_LOG_DOMAIN, "ibv_destroy_ah failed during cleanup! err=%d\n", ret);
			HASH_DEL(efa_domain->ah_map, ah_entry);
			free(ah_entry);
		}
	}
	ofi_genlock_unlock(&efa_domain->util_domain.lock);
}
