/* SPDX-License-Identifier: BSD-2-Clause OR GPL-2.0-only */
/* SPDX-FileCopyrightText: Copyright Amazon.com, Inc. or its affiliates. All rights reserved. */

#include <assert.h>
#include <ofi_util.h>

#include "config.h"
#include "efa.h"
#include "efa_domain_util.h"

/**
 * @brief Create the bufpool backing efa_mr/efa_rdm_mr instances on an
 * efa_domain.
 *
 * Caller passes the entry size: efa_domain_open passes
 * sizeof(struct efa_mr); efa_rdm_domain_open passes
 * sizeof(struct efa_rdm_mr). Pool is freed on close via the
 * type-agnostic efa_mr_pool_destroy.
 *
 * @param[in,out] efa_domain  Domain whose pool will be created.
 * @param[in]     entry_size  Size of each pooled MR entry.
 * @return 0 on success, negative libfabric error code on failure.
 */
int efa_mr_pool_create(struct efa_domain *efa_domain, size_t entry_size)
{
	int ret;

	ret = ofi_bufpool_create(&efa_domain->mr_pool,
				 entry_size,
				 EFA_RDM_BUFPOOL_ALIGNMENT, 0, 0, 0);
	if (ret) {
		EFA_WARN(FI_LOG_DOMAIN, "mr_pool init failed! err: %d\n", ret);
		return ret;
	}

	return 0;
}

/**
 * @brief Destroy any MR bufpools created by efa_mr_pool_create.
 *
 * @param[in,out] efa_domain  Domain whose pools will be destroyed.
 */
static void efa_mr_pool_destroy(struct efa_domain *efa_domain)
{
	if (efa_domain->mr_pool) {
		ofi_bufpool_destroy(efa_domain->mr_pool);
		efa_domain->mr_pool = NULL;
	}
}

int efa_domain_init_base(struct efa_domain *efa_domain,
			 struct fid_fabric *fabric_fid,
			 struct fi_info *info,
			 void *context)
{
	int err;

	/* This list_entry is not the head of the list. But we initialize it
	 * anyway to prevent a segfault in the close path: dlist_remove on a
	 * self-looped entry is a no-op, so a partial-init close that runs
	 * before insertion into g_efa_domain_list is safe.
	 */
	dlist_init(&efa_domain->list_entry);
	efa_domain->fabric = container_of(fabric_fid, struct efa_fabric,
					  util_fabric.fabric_fid);

	err = ofi_domain_init(fabric_fid, info, &efa_domain->util_domain,
			      context, OFI_LOCK_MUTEX);
	if (err)
		return err;

	ofi_atomic_initialize64(&efa_domain->ibv_mr_reg_ct, 0);
	ofi_atomic_initialize64(&efa_domain->ibv_mr_reg_sz, 0);

	efa_domain->ah_map = NULL;

	efa_domain->util_domain.av_type = FI_AV_TABLE;
	efa_domain->util_domain.mr_map.mode |= FI_MR_VIRT_ADDR;
	/*
	 * FI_MR_PROV_KEY means provider will generate a key for MR,
	 * which EFA provider does by using key generated by EFA device.
	 *
	 * util_domain.mr_map.mode is same as info->mode, which has
	 * the bit FI_MR_PROV_KEY on. When the bit is on, util_domain.mr_map
	 * will generate a key for MR, which is not what we want
	 * (we want to use the key generated by device). Therefore unset
	 * the FI_MR_PROV_KEY bit of mr_map.
	 */
	efa_domain->util_domain.mr_map.mode &= ~FI_MR_PROV_KEY;

	if (!info->ep_attr || info->ep_attr->type == FI_EP_UNSPEC) {
		EFA_WARN(FI_LOG_DOMAIN, "ep type not specified when creating domain\n");
		return -FI_EINVAL;
	}

	efa_domain->mr_local = ofi_mr_local(info);

	err = efa_domain_init_device_and_pd(efa_domain, info->domain_attr->name,
					    info->ep_attr->type);
	if (err)
		return err;

	efa_domain->info = fi_dupinfo(EFA_EP_TYPE_IS_RDM(info)
				      ? efa_domain->device->rdm_info
				      : efa_domain->device->dgram_info);
	if (!efa_domain->info)
		return -FI_ENOMEM;

	/* keep max_cntr_value and max_err_cntr_value from user info so we can
	 * decide whether to use hw counter later */
	efa_domain->info->domain_attr->max_cntr_value = info->domain_attr->max_cntr_value;
	efa_domain->info->domain_attr->max_err_cntr_value = info->domain_attr->max_err_cntr_value;

	if (efa_env.track_mr)
		dlist_init(&efa_domain->base_ep_list);

	return 0;
}

int efa_domain_finalize_base(struct efa_domain *efa_domain)
{
#ifndef _WIN32
	int err = efa_fork_support_install_fork_handler();
	if (err) {
		EFA_WARN(FI_LOG_CORE,
			 "Unable to install fork handler: %s\n",
			 strerror(-err));
		return err;
	}
#endif

	ofi_mutex_lock(&g_efa_domain_list_lock);
	dlist_insert_tail(&efa_domain->list_entry, &g_efa_domain_list);
	ofi_mutex_unlock(&g_efa_domain_list_lock);

	return 0;
}

void efa_domain_remove_from_global_list(struct efa_domain *efa_domain)
{
	ofi_mutex_lock(&g_efa_domain_list_lock);
	dlist_remove(&efa_domain->list_entry);
	ofi_mutex_unlock(&g_efa_domain_list_lock);
}

void efa_domain_cleanup_ah_map(struct efa_domain *efa_domain)
{
	struct efa_ah *ah_entry, *tmp;
	int ret;

	ofi_genlock_lock(&efa_domain->util_domain.lock);
	if (efa_domain->ah_map) {
		EFA_WARN(FI_LOG_DOMAIN, "AH map not empty during domain close! Cleaning up ...\n");
		HASH_ITER(hh, efa_domain->ah_map, ah_entry, tmp) {
			ret = ibv_destroy_ah(ah_entry->ibv_ah);
			if (ret)
				EFA_WARN(FI_LOG_DOMAIN, "ibv_destroy_ah failed during cleanup! err=%d\n", ret);
			HASH_DEL(efa_domain->ah_map, ah_entry);
			free(ah_entry);
		}
	}
	ofi_genlock_unlock(&efa_domain->util_domain.lock);
}

void efa_domain_destruct(struct efa_domain *efa_domain)
{
	int ret;

	efa_domain_remove_from_global_list(efa_domain);
	efa_domain_cleanup_ah_map(efa_domain);

	efa_mr_pool_destroy(efa_domain);

	if (efa_domain->ibv_pd) {
		ret = ibv_dealloc_pd(efa_domain->ibv_pd);
		if (ret)
			EFA_WARN(FI_LOG_DOMAIN, "Failed to dealloc ibv_pd: %d\n", ret);
		efa_domain->ibv_pd = NULL;
	}

	ret = ofi_domain_close(&efa_domain->util_domain);
	if (ret)
		EFA_WARN(FI_LOG_DOMAIN, "Failed to close util_domain: %d\n", ret);

	if (efa_domain->info) {
		fi_freeinfo(efa_domain->info);
		efa_domain->info = NULL;
	}

	if (efa_domain->device)
		ofi_atomic_dec32(&efa_domain->device->ref_cnt);
}
