# SPDX-License-Identifier: GPL-2.0
#
# Copyright 2018,2020-2022 Cray Inc. All rights reserved.

if HAVE_CXI

AM_CPPFLAGS += \
	-I$(top_srcdir)/prov/cxi/include \
	-I$(top_srcdir)/prov/cxi \
	-I$(srcdir)/../cxi-driver/include \
	-I$(srcdir)/../cassini-headers/install/include

_cxi_files = \
	prov/cxi/src/cxip_if.c \
	prov/cxi/src/cxip_fabric.c \
	prov/cxi/src/cxip_repsum.c \
	prov/cxi/src/cxip_coll.c \
	prov/cxi/src/cxip_zbcoll.c \
	prov/cxi/src/cxip_curl.c \
	prov/cxi/src/cxip_dom.c \
	prov/cxi/src/cxip_ep.c \
	prov/cxi/src/cxip_txc.c \
	prov/cxi/src/cxip_rxc.c \
	prov/cxi/src/cxip_av.c \
	prov/cxi/src/cxip_avset.c \
	prov/cxi/src/cxip_eq.c \
	prov/cxi/src/cxip_cq.c \
	prov/cxi/src/cxip_cntr.c \
	prov/cxi/src/cxip_rma.c \
	prov/cxi/src/cxip_mr.c \
	prov/cxi/src/cxip_msg.c \
	prov/cxi/src/cxip_atomic.c \
	prov/cxi/src/cxip_iomm.c \
	prov/cxi/src/cxip_faults.c \
	prov/cxi/src/cxip_info.c \
	prov/cxi/src/cxip_ctrl.c \
	prov/cxi/src/cxip_req_buf.c \
	prov/cxi/src/cxip_rdzv_pte.c \
	prov/cxi/src/cxip_telemetry.c \
	prov/cxi/src/cxip_ptelist_buf.c

_cxi_headers = \
	prov/cxi/include/cxip.h \
	prov/cxi/include/cxip_faults.h \
	prov/cxi/include/fi_cxi_ext.h

rdmainclude_HEADERS += \
	prov/cxi/include/fi_cxi_ext.h

_cxi_libs = \
	-lcurl -ljson-c -lm

if HAVE_PMI

# Stand-alone srun tests for hardware testing environment
bin_PROGRAMS += prov/cxi/test/distributed/pmi_launch
prov_cxi_test_distributed_pmi_launch_SOURCES = \
	prov/cxi/test/distributed/pmi_utils.h \
	prov/cxi/test/distributed/pmi_utils.c \
	prov/cxi/test/distributed/pmi_launch.c
prov_cxi_test_distributed_pmi_launch_CPPFLAGS = -DUSE_PMI2
prov_cxi_test_distributed_pmi_launch_LDFLAGS = -static -lpmi2

bin_PROGRAMS += prov/cxi/test/distributed/pmi_launch_test
prov_cxi_test_distributed_pmi_launch_test_SOURCES = \
	prov/cxi/test/distributed/pmi_launch_test.c

bin_PROGRAMS += prov/cxi/test/distributed/test_pmi
prov_cxi_test_distributed_test_pmi_SOURCES = \
	prov/cxi/test/distributed/pmi_utils.h \
	prov/cxi/test/distributed/pmi_utils.c \
	prov/cxi/test/distributed/test_pmi.c
prov_cxi_test_distributed_test_pmi_CPPFLAGS = -DUSE_PMI2
prov_cxi_test_distributed_test_pmi_LDFLAGS = -static -lpmi2

bin_PROGRAMS += prov/cxi/test/distributed/test_frmwk
prov_cxi_test_distributed_test_frmwk_SOURCES = \
	prov/cxi/test/distributed/pmi_utils.h \
	prov/cxi/test/distributed/pmi_utils.c \
	prov/cxi/test/distributed/pmi_frmwk.h \
	prov/cxi/test/distributed/pmi_frmwk.c \
	prov/cxi/test/distributed/test_frmwk.c
prov_cxi_test_distributed_test_frmwk_CPPFLAGS = \
	$(AM_CPPFLAGS) $(cxi_CPPFLAGS) $(PTHREAD_FLAGS) \
	-DUSE_PMI2
prov_cxi_test_distributed_test_frmwk_LDFLAGS = -static -lpmi2
prov_cxi_test_distributed_test_frmwk_LDADD = $(linkback) $(PTHREAD_LIBS)

bin_PROGRAMS += prov/cxi/test/distributed/test_zbcoll
prov_cxi_test_distributed_test_zbcoll_SOURCES = \
	prov/cxi/test/distributed/pmi_utils.h \
	prov/cxi/test/distributed/pmi_utils.c \
	prov/cxi/test/distributed/pmi_frmwk.h \
	prov/cxi/test/distributed/pmi_frmwk.c \
	prov/cxi/test/distributed/test_zbcoll.c
prov_cxi_test_distributed_test_zbcoll_CPPFLAGS = \
	$(AM_CPPFLAGS) $(cxi_CPPFLAGS) $(PTHREAD_FLAGS) \
	-DUSE_PMI2
prov_cxi_test_distributed_test_zbcoll_LDFLAGS = -static -lpmi2
prov_cxi_test_distributed_test_zbcoll_LDADD = $(linkback) $(PTHREAD_LIBS)

bin_PROGRAMS += prov/cxi/test/distributed/test_coll
prov_cxi_test_distributed_test_coll_SOURCES = \
	prov/cxi/test/distributed/pmi_utils.h \
	prov/cxi/test/distributed/pmi_utils.c \
	prov/cxi/test/distributed/pmi_frmwk.h \
	prov/cxi/test/distributed/pmi_frmwk.c \
	prov/cxi/test/distributed/test_coll.c
prov_cxi_test_distributed_test_coll_CPPFLAGS = \
	$(AM_CPPFLAGS) $(cxi_CPPFLAGS) $(PTHREAD_FLAGS) \
	-DUSE_PMI2
prov_cxi_test_distributed_test_coll_LDFLAGS = -static -lpmi2
prov_cxi_test_distributed_test_coll_LDADD = $(linkback) $(PTHREAD_LIBS)

endif HAVE_PMI

if HAVE_CRITERION

# curltest is not expected to exist outside devel env
bin_PROGRAMS += prov/cxi/test/curltest
prov_cxi_test_curltest_SOURCES = \
	prov/cxi/test/curl.c
prov_cxi_test_curltest_CPPFLAGS = $(AM_CPPFLAGS) $(cxi_CPPFLAGS) \
	$(cxitest_CPPFLAGS) $(PTHREAD_CFLAGS)
prov_cxi_test_curltest_LDFLAGS = $(cxitest_LDFLAGS) -static
prov_cxi_test_curltest_LDADD =  $(cxitest_LIBS) $(linkback) $(PTHREAD_LIBS)

bin_PROGRAMS += prov/cxi/test/cxitest
nodist_prov_cxi_test_cxitest_SOURCES = \
	prov/cxi/test/cxip_test_common.c \
	prov/cxi/test/fabric.c \
	prov/cxi/test/domain.c \
	prov/cxi/test/ep.c \
	prov/cxi/test/eq.c \
	prov/cxi/test/cq.c \
	prov/cxi/test/av.c \
	prov/cxi/test/avset.c \
	prov/cxi/test/rma.c \
	prov/cxi/test/sep.c \
	prov/cxi/test/tagged.c \
	prov/cxi/test/msg.c \
	prov/cxi/test/atomic.c \
	prov/cxi/test/cntr.c \
	prov/cxi/test/tagged_stress.c \
	prov/cxi/test/mr.c \
	prov/cxi/test/deferred_work.c \
	prov/cxi/test/coll.c \
	prov/cxi/test/ctrl.c \
	prov/cxi/test/lat.c \
	prov/cxi/test/repsum.c \
	prov/cxi/test/auth_key.c

prov_cxi_test_cxitest_CPPFLAGS = $(AM_CPPFLAGS) $(cxi_CPPFLAGS) \
	$(cxitest_CPPFLAGS) $(PTHREAD_CFLAGS)
prov_cxi_test_cxitest_LDFLAGS = $(cxitest_LDFLAGS) -static
prov_cxi_test_cxitest_LDADD =  $(cxitest_LIBS) $(linkback) $(PTHREAD_LIBS)

TESTS += prov/cxi/test/cxitest

endif HAVE_CRITERION

if HAVE_CXI_DL
pkglib_LTLIBRARIES += libcxi-fi.la
libcxi_fi_la_SOURCES = $(_cxi_files) $(_cxi_headers) $(common_srcs)
libcxi_fi_la_CPPFLAGS = $(cxi_CPPFLAGS)
libcxi_fi_la_LIBADD = $(linkback) $(cxi_LIBS) $(_cxi_libs)
libcxi_fi_la_LDFLAGS = $(cxi_LDFLAGS) \
	-module -avoid-version -shared -export-dynamic
libcxi_fi_la_DEPENDENCIES = $(linkback)
else !HAVE_CXI_DL
src_libfabric_la_SOURCES += $(_cxi_files) $(_cxi_headers)
src_libfabric_la_CPPFLAGS += $(cxi_CPPFLAGS)
src_libfabric_la_LIBADD += $(cxi_LIBS) $(_cxi_libs)
src_libfabric_la_LDFLAGS += $(cxi_LDFLAGS)
endif !HAVE_CXI_DL

prov_install_man_pages += man/man7/fi_cxi.7

endif HAVE_CXI

prov_dist_man_pages += man/man7/fi_cxi.7
