if HAVE_VERBS
_verbs_files =							\
	prov/verbs/src/fi_verbs.h				\
	prov/verbs/src/fi_verbs.c				\
	prov/verbs/src/verbs_cm.c				\
	prov/verbs/src/verbs_cq.c				\
	prov/verbs/src/verbs_srq.c				\
	prov/verbs/src/verbs_domain.c				\
	prov/verbs/src/verbs_mr.c				\
	prov/verbs/src/verbs_eq.c				\
	prov/verbs/src/verbs_info.c				\
	prov/verbs/src/verbs_msg_ep.c				\
	prov/verbs/src/ep_rdm/verbs_av_ep_rdm.c			\
	prov/verbs/src/ep_rdm/verbs_cq_ep_rdm.c			\
	prov/verbs/src/ep_rdm/verbs_ep_rdm.c			\
	prov/verbs/src/ep_rdm/verbs_queuing.h			\
	prov/verbs/src/ep_rdm/verbs_rdm_cm.c			\
	prov/verbs/src/ep_rdm/verbs_rdm_cntr.c			\
	prov/verbs/src/ep_rdm/verbs_rdm_msg.c			\
	prov/verbs/src/ep_rdm/verbs_rdm_rma.c			\
	prov/verbs/src/ep_rdm/verbs_rdm.h			\
	prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm_states.h	\
	prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm_states.c	\
	prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm.c		\
	prov/verbs/src/ep_rdm/verbs_utils.c			\
	prov/verbs/src/ep_rdm/verbs_utils.h			\
	prov/verbs/src/ep_dgram/verbs_dgram.h			\
	prov/verbs/src/ep_dgram/verbs_dgram_ep.c		\
	prov/verbs/src/ep_dgram/verbs_dgram_ep_msg.c		\
	prov/verbs/src/ep_dgram/verbs_dgram_cq.c		\
	prov/verbs/src/ep_dgram/verbs_dgram_cntr.c		\
	prov/verbs/src/ep_dgram/verbs_dgram_av.c

if HAVE_VERBS_DL
pkglib_LTLIBRARIES += libverbs-fi.la
libverbs_fi_la_SOURCES = $(_verbs_files) $(common_srcs)
libverbs_fi_la_CPPFLAGS = 			\
	-I$(top_srcdir)/include			\
	-I$(top_srcdir)/prov/verbs/src/ep_rdm	\
	-I$(top_srcdir)/prov/verbs/src/ep_dgram	\
	$(AM_CPPFLAGS) $(verbs_CPPFLAGS)
libverbs_fi_la_LDFLAGS =				\
	-module -avoid-version -shared -export-dynamic	\
	$(verbs_LDFLAGS)
libverbs_fi_la_LIBADD = $(linkback) $(verbs_LIBS)
libverbs_fi_la_DEPENDENCIES = $(linkback)
else !HAVE_VERBS_DL
src_libfabric_la_SOURCES += $(_verbs_files)
src_libfabric_la_CPPFLAGS += 			\
	-I$(top_srcdir)/prov/verbs/src/ep_rdm	\
	-I$(top_srcdir)/prov/verbs/src/ep_dgram	\
	$(verbs_CPPFLAGS)
src_libfabric_la_LDFLAGS += $(verbs_LDFLAGS)
src_libfabric_la_LIBADD += $(verbs_LIBS)
endif !HAVE_VERBS_DL

prov_install_man_pages += man/man7/fi_verbs.7

endif HAVE_VERBS

prov_dist_man_pages += man/man7/fi_verbs.7
