
pipeline {
    agent { node { label 'master' } }
    options {
        timestamps()
        timeout(activity: true, time: 4, unit: 'HOURS')
    }
    environment {
        JOB_CADENCE = 'PR'
    }

    stages {
        stage ('build-libfabric') {
            steps {
                withEnv(['PATH+EXTRA=/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin']) {
                  sh """
                    python3.7 contrib/intel/jenkins/build.py 'libfabric' --ofi_build_mode='dbg'
                    echo "libfabric build completed"
                  """
                }
            }
        }
        stage('build-fabtests') {
            steps {
                withEnv(['PATH+EXTRA=/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin']) {
                  sh """
                    python3.7 contrib/intel/jenkins/build.py 'fabtests' --ofi_build_mode='dbg'
                    echo 'fabtests build completed'
                  """
                }
            }
        }
        stage ('copy-build-dirs') {
            steps {
                withEnv(['PATH+EXTRA=/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin']) {
                  sh """
                    python3.7 contrib/intel/jenkins/build.py 'builddir' --ofi_build_mode='dbg'
                    echo "copy build dirs complete"
                  """
                }
            }
        }
        stage('parallel-tests') {
            parallel {
                stage('eth-tcp-dbg') {
                    agent {node {label 'eth'}}
                    steps {
                        withEnv(['PATH+EXTRA=/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin/:$PYTHONPATH'])
                        {
                          sh """
                            env
                            (
                                cd  ${env.WORKSPACE}/contrib/intel/jenkins/
                                python3.7 runtests.py --prov=tcp --ofi_build_mode='dbg'
                            )
                          """
                        }
                    }
                }
                stage('eth-udp-shm-dbg') {
                    agent {node {label 'eth'}}
                    steps {
                        withEnv(['PATH+EXTRA=/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin/:$PYTHONPATH'])
                        {
                          sh """
                            env
                            (
                                cd  ${env.WORKSPACE}/contrib/intel/jenkins/
                                python3.7 runtests.py --prov=udp --ofi_build_mode='dbg'
                                python3.7 runtests.py --prov=udp --util=rxd --ofi_build_mode='dbg'
                                python3.7 runtests.py --prov=shm --ofi_build_mode='dbg'
                            )
                          """
                        }
                    }
                }
                stage('mlx5-verbs_rxm-dbg') {
                    agent {node {label 'mlx5'}}
                    steps {
                        withEnv(['PATH+EXTRA=/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin:$PYTHONPATH']) {
                          sh """
                            env
                            (
                                cd ${env.WORKSPACE}/contrib/intel/jenkins/
                                python3.7 runtests.py --prov=verbs --ofi_build_mode='dbg'
                                python3.7 runtests.py --prov=verbs --util=rxm --ofi_build_mode='dbg'
                            )
                          """
                        }
                    }
                }
                stage('mlx5-verbs_rxd-dbg') {
                    agent {node {label 'mlx5'}}
                    steps {
                        withEnv(['PATH+EXTRA=/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin:$PYTHONPATH']) {
                          sh """
                            env
                            (
                                cd ${env.WORKSPACE}/contrib/intel/jenkins/
                                python3.7 runtests.py --prov=verbs --util=rxd --ofi_build_mode='dbg'
                            )
                          """
                        }
                    }
                }
            }
        }
    }

    post {
        cleanup {
            withEnv(['PATH+EXTRA=/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin:$PYTHONPATH']) {
                dir("${env.WORKSPACE}") {
                    sh "rm -rf '${env.CI_INSTALL_DIR}/${env.JOB_NAME}/${env.BUILD_NUMBER}/ci_middlewares'"
                    deleteDir()
                }
            }
        }
    }
}
