name: clang-format-cn Check
on: workflow_dispatch
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'prov/opx'
    steps:
    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
    - name: Run clang-format style check for C/C++/Protobuf programs (Cornelis Networks-specific).
      uses: jidicula/clang-format-action@c74383674bf5f7c69f60ce562019c1c94bc1421a # v4.13.0
      with:
        clang-format-version: '15'
        check-path: ${{ matrix.path }}
