name: clang-format Check
on: [push, pull_request]
permissions:
  contents: read
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'prov/sm2'
          - 'bindings/rust'
    steps:
    - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v4.3.1
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@654a770daa28443dd111d133e4083e21c1075674 # v4.18.0
      with:
        clang-format-version: '15'
        check-path: ${{ matrix.path }}
